config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    before_validation :set_default_price
    before_validation :set_default_participants

    validates :title, presence: true, uniquness: true
    validates :description, presence: true, length: {minimum: 100}
    validates :location, presence: true
    validates :price, presence: true
    validates :image, presence: true
    validates :participants, presence: true, numericality: {less_than: 21}
    validates :start_time, presence: true

    private
    def set_default_price
        self.price ||=0
    end
    def set_default_participants
        self.participants ||=0
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def create
        @event = Event.new event_params
        if @event.save
            flash[:notice] = 'event created'
        else 
            render :new
        end
    end
    def new
        @event = Event.new
    end
    def show
        @event = Event.find params[:id]
    end
    def index
        @event = Event.all
    end
    def edit
    end
    def delete
        flash[:notice] = 'Event deleted'
        @event.deleted
    end
    private
    def event_params
        params.require(:event).permit(:title, :description, :price, :image, :participants, :start_time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        # form_with uses an instance to create a form
      end
      def create
        @user = User.new params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        if @user.save
          flash.delete(:warning)
          redirect_to events_path
        else
          flash[:warning] = "unable to create user"
          render :new
        end
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/new.html.erb
<h2>Create your new event</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evently</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <nav>
  <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQXJ7xW5NzUw_4OUgy70MOsNtqK9lHDM6OjuQ&usqp=CAU' >
<a><%= link_to 'View Events', events_path%></a>
<a><%= link_to 'Post Events', new_event_path%></a>
</nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>User New Page</h1>
<% if @user.errors.present? %>
  <p>
    <%= @user.errors.full_messages.join(', ')%>
  </p>
<% end %>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: @user, local: true do |f| %>
    <div class='form-group'>
      <%= f.label :first_name%>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :last_name%>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :email%>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password%>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Create User", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>This is evently here you can see all the events you own.Click on "View events" to see more events near you.</p>